services:
  bacalah.api:
    image: bacalah.api
    build:
      context: .
      dockerfile: bacalah.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost;Port=3306;Database=bacalah_db;Uid=root;Pwd=password123;
    depends_on:
      - mysql
    ports:
      - "5141:8080"
    networks:
      - bacalah_net
  
  mysql:
    image: mysql:8.0
    container_name: bacalah_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: bacalah_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bacalah_net

volumes:
  mysql_data:

networks:
  bacalah_net:
    driver: bridge